services:
  - type: web
    name: hackrx-rag-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL_NAME
        value: gemini-2.0-flash
      - key: API_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false